name: Setup project
on:
  push:
    branchs: [ stage, main, master ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing root dependencies
        run: |
          composer install -o
